name = "picasso-fe"
type = "javascript"  # Hoặc "webpack" nếu bạn cần build trước

account_id = "4d6ae1b278be4d159deb9e18974b2cc9"
workers_dev = true
route = ""
zone_id = ""
main = "src/main.ts"

compatibility_date = "2025-03-07"
